function MainAdmin() {
  return (
    <div className="">
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
      <p>ttttttttttttttttttttttttttt</p>
    </div>
  );
}

export default MainAdmin;
